<?php

// Create table
$object -> sql_query("CREATE TABLE IF NOT EXISTS `fwstate` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `HARDWARE_ID` int(11) NOT NULL,
  `DOMAINSTATE` varchar(255) DEFAULT NULL,
  `PRIVATESTATE` varchar(255) DEFAULT NULL,
  `PUBLICSTATE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`,`HARDWARE_ID`)
)  ENGINE=INNODB ;");

?>
